from __future__ import annotations

from fastapi import APIRouter
from fastapi.responses import HTMLResponse

from ..services.request_inspector import inspector

router = APIRouter(prefix="/inspect", tags=["inspect"])


@router.get("", response_class=HTMLResponse)
def inspect_dashboard():
    return """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>JanSahayak Request Inspector</title>
  <style>
    :root {
      --bg: #f4efe5;
      --panel: #fffaf2;
      --ink: #1f2937;
      --muted: #6b7280;
      --line: #dfd2ba;
      --accent: #0f766e;
      --accent-soft: #d7f3ef;
      --code: #1b1f23;
    }
    * { box-sizing: border-box; }
    body {
      margin: 0;
      font-family: Georgia, "Times New Roman", serif;
      color: var(--ink);
      background:
        radial-gradient(circle at top left, #fff6dc 0, transparent 30%),
        linear-gradient(180deg, #efe4d1 0, var(--bg) 38%, #f8f4ec 100%);
    }
    .wrap {
      max-width: 1200px;
      margin: 0 auto;
      padding: 32px 20px 56px;
    }
    .hero {
      display: flex;
      justify-content: space-between;
      gap: 16px;
      align-items: end;
      margin-bottom: 24px;
    }
    h1 {
      margin: 0;
      font-size: clamp(2rem, 4vw, 3.4rem);
      line-height: 0.95;
    }
    .sub {
      margin-top: 8px;
      color: var(--muted);
      max-width: 700px;
      font-size: 1rem;
    }
    .actions {
      display: flex;
      gap: 10px;
      flex-wrap: wrap;
    }
    button {
      border: 1px solid var(--line);
      background: var(--panel);
      color: var(--ink);
      padding: 10px 14px;
      border-radius: 999px;
      cursor: pointer;
      font: inherit;
    }
    button.primary {
      background: var(--accent);
      color: white;
      border-color: var(--accent);
    }
    .grid {
      display: grid;
      grid-template-columns: 340px 1fr;
      gap: 18px;
    }
    .panel {
      background: color-mix(in srgb, var(--panel) 92%, white);
      border: 1px solid var(--line);
      border-radius: 20px;
      overflow: hidden;
      box-shadow: 0 10px 35px rgba(31, 41, 55, 0.08);
    }
    .panel-head {
      padding: 16px 18px;
      border-bottom: 1px solid var(--line);
      background: rgba(255,255,255,0.45);
    }
    .panel-head strong { font-size: 1.05rem; }
    .list {
      max-height: 72vh;
      overflow: auto;
    }
    .item {
      width: 100%;
      text-align: left;
      border: 0;
      border-bottom: 1px solid var(--line);
      border-radius: 0;
      padding: 14px 18px;
      background: transparent;
      display: block;
    }
    .item:hover, .item.active {
      background: var(--accent-soft);
    }
    .meta {
      display: flex;
      justify-content: space-between;
      gap: 12px;
      font-size: 0.9rem;
      color: var(--muted);
      margin-top: 6px;
    }
    .badge {
      display: inline-block;
      font-size: 0.8rem;
      padding: 4px 8px;
      border-radius: 999px;
      background: rgba(15, 118, 110, 0.11);
      color: var(--accent);
      margin-left: 8px;
    }
    .detail {
      padding: 20px;
    }
    .empty {
      color: var(--muted);
      padding: 24px 20px;
    }
    .detail-top {
      display: flex;
      justify-content: space-between;
      gap: 12px;
      align-items: start;
      flex-wrap: wrap;
      margin-bottom: 18px;
    }
    .detail-top h2 {
      margin: 0 0 6px;
      font-size: 1.5rem;
    }
    .detail-top p {
      margin: 0;
      color: var(--muted);
    }
    .section {
      margin-top: 18px;
    }
    .section h3 {
      margin: 0 0 8px;
      font-size: 1rem;
      text-transform: uppercase;
      letter-spacing: 0.08em;
      color: var(--muted);
    }
    pre {
      margin: 0;
      padding: 16px;
      background: #fff;
      border: 1px solid var(--line);
      border-radius: 16px;
      overflow: auto;
      color: var(--code);
      font-size: 0.92rem;
      line-height: 1.45;
    }
    @media (max-width: 900px) {
      .grid { grid-template-columns: 1fr; }
      .list { max-height: none; }
    }
  </style>
</head>
<body>
  <div class="wrap">
    <div class="hero">
      <div>
        <h1>Request Inspector</h1>
        <div class="sub">Open this on Railway to review recent incoming requests and the exact responses generated by the app.</div>
      </div>
      <div class="actions">
        <button onclick="loadEntries()">Refresh</button>
        <button class="primary" onclick="clearEntries()">Clear</button>
      </div>
    </div>
    <div class="grid">
      <div class="panel">
        <div class="panel-head"><strong>Recent Requests</strong></div>
        <div id="request-list" class="list"></div>
      </div>
      <div class="panel">
        <div id="detail" class="detail">
          <div class="empty">No requests yet. Send a chat, Twilio WhatsApp message, or voice request, then refresh.</div>
        </div>
      </div>
    </div>
  </div>
  <script>
    let entries = [];
    let activeId = null;

    function pretty(value) {
      return JSON.stringify(value, null, 2);
    }

    function formatTime(value) {
      try {
        return new Date(value).toLocaleString();
      } catch {
        return value;
      }
    }

    function renderList() {
      const root = document.getElementById('request-list');
      if (!entries.length) {
        root.innerHTML = '<div class="empty">No captured requests yet.</div>';
        return;
      }
      root.innerHTML = entries.map((entry) => `
        <button class="item ${entry.id === activeId ? 'active' : ''}" onclick="selectEntry('${entry.id}')">
          <div><strong>${entry.method} ${entry.path}</strong><span class="badge">${entry.channel}</span></div>
          <div class="meta">
            <span>${entry.status_code}</span>
            <span>${formatTime(entry.timestamp)}</span>
          </div>
        </button>
      `).join('');
    }

    function renderDetail() {
      const root = document.getElementById('detail');
      const entry = entries.find((item) => item.id === activeId) || entries[0];
      if (!entry) {
        root.innerHTML = '<div class="empty">No requests yet. Send a request and refresh.</div>';
        return;
      }
      activeId = entry.id;
      root.innerHTML = `
        <div class="detail-top">
          <div>
            <h2>${entry.method} ${entry.path}</h2>
            <p>${formatTime(entry.timestamp)} | ${entry.channel} | status ${entry.status_code}</p>
          </div>
        </div>
        <div class="section">
          <h3>Request</h3>
          <pre>${escapeHtml(pretty(entry.request))}</pre>
        </div>
        <div class="section">
          <h3>Response</h3>
          <pre>${escapeHtml(pretty(entry.response))}</pre>
        </div>
      `;
    }

    function escapeHtml(text) {
      return text
        .replaceAll('&', '&amp;')
        .replaceAll('<', '&lt;')
        .replaceAll('>', '&gt;');
    }

    async function loadEntries() {
      const response = await fetch('/inspect/requests');
      entries = await response.json();
      if (!activeId && entries[0]) activeId = entries[0].id;
      if (activeId && !entries.some((entry) => entry.id === activeId) && entries[0]) {
        activeId = entries[0].id;
      }
      renderList();
      renderDetail();
    }

    function selectEntry(id) {
      activeId = id;
      renderList();
      renderDetail();
    }

    async function clearEntries() {
      await fetch('/inspect/requests', { method: 'DELETE' });
      entries = [];
      activeId = null;
      renderList();
      renderDetail();
    }

    loadEntries();
    setInterval(loadEntries, 5000);
  </script>
</body>
</html>"""


@router.get("/requests")
def list_requests():
    return inspector.list_entries()


@router.delete("/requests")
def clear_requests():
    inspector.clear()
    return {"status": "ok"}


@router.get("/requests/latest")
def latest_request():
    entries = inspector.list_entries()
    return entries[0] if entries else {"status": "empty"}
